#cloud-config
write_files:
- path: /etc/systemd/system/httpd.service
  permissions: 0644
  owner: root
  content: |
    [Unit]
    Description=httpd container

    [Service]
    ExecStart=/usr/bin/docker run --rm --publish 80:80 --name=httpd httpd:alpine
    ExecStop=/usr/bin/docker stop httpd
    ExecStopPost=/usr/bin/docker rm httpd

runcmd:
- systemctl daemon-reload
- systemctl start httpd.service
